# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: true
    error_controller: 'App\Controller\ErrorController::show'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

        # Durée de vie de la session
        cookie_lifetime: 360000  # Durée de vie des cookies de session en secondes
        # 24 heures pour les cookies
        gc_maxlifetime: 3600   # Durée de vie des données de session en secondes
        # 1 heure pour les données de session

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
